services:
  - type: web
    name: medical-report-extract-ai
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PRIMARY_GEMINI_API_KEY
        sync: false
      - key: FALLBACK_GEMINI_API_KEY
        sync: false
      - key: PORT
        value: "10000"
